// Shared helpers for validate.mjs and build-index.mjs. No dependencies by design.
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const KB_DIR = join(ROOT, 'kb');
export const INDEX_DIR = join(ROOT, 'index');

/** folder name -> entry type */
export const FOLDER_TYPE = {
  principles: 'principle',
  patterns: 'pattern',
  practices: 'practice',
  rfcs: 'rfc',
  decisions: 'decision',
};

export const TYPE_ORDER = ['principle', 'pattern', 'practice', 'rfc', 'decision'];

export const VOCAB = {
  status: ['draft', 'stable', 'deprecated', 'superseded'],
  domains: [
    'architecture', 'backend', 'frontend', 'data',
    'messaging', 'platform', 'observability', 'security',
    'testing', 'delivery', 'ai', 'agentic',
    'people',
  ],
};

export const REQUIRED = ['id', 'title', 'type', 'status', 'summary', 'domains', 'created', 'updated'];
export const LIST_FIELDS = ['domains', 'stack', 'related', 'supersedes', 'sources'];

const unquote = (s) => {
  const t = s.trim();
  if ((t.startsWith('"') && t.endsWith('"')) || (t.startsWith("'") && t.endsWith("'"))) {
    return t.slice(1, -1);
  }
  return t;
};

/**
 * Deliberately small YAML subset: scalars, quoted strings, inline [a, b] arrays and
 * `- item` block lists. No nesting, anchors or multi-line scalars. See docs/frontmatter.md.
 */
export function parseFrontmatter(text) {
  const lines = text.split(/\r?\n/);
  if (lines[0]?.trim() !== '---') return { data: null, body: text };
  const end = lines.indexOf('---', 1);
  if (end === -1) return { data: null, body: text };

  const data = {};
  let currentKey = null;
  for (const raw of lines.slice(1, end)) {
    const line = raw.replace(/\s+$/, '');
    if (!line.trim() || line.trim().startsWith('#')) continue;

    const item = line.match(/^\s*-\s+(.*)$/);
    if (item && currentKey) {
      (data[currentKey] ||= []).push(unquote(item[1]));
      continue;
    }

    const kv = line.match(/^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$/);
    if (!kv) continue;
    const [, key, rest] = kv;
    currentKey = key;

    if (rest === '') {
      data[key] = [];
    } else if (rest.startsWith('[') && rest.endsWith(']')) {
      data[key] = rest
        .slice(1, -1)
        .split(',')
        .map(unquote)
        .filter(Boolean);
    } else {
      data[key] = unquote(rest);
    }
  }

  for (const f of LIST_FIELDS) {
    if (f in data && !Array.isArray(data[f])) data[f] = [data[f]].filter(Boolean);
  }

  return { data, body: lines.slice(end + 1).join('\n') };
}

/** All non-template entries under kb/, with parsed frontmatter. */
export function loadEntries() {
  const entries = [];
  for (const folder of Object.keys(FOLDER_TYPE)) {
    const dir = join(KB_DIR, folder);
    let names;
    try {
      names = readdirSync(dir);
    } catch {
      continue;
    }
    for (const name of names.sort()) {
      if (!name.endsWith('.md') || name.startsWith('_')) continue;
      const path = join(dir, name);
      if (!statSync(path).isFile()) continue;
      const text = readFileSync(path, 'utf8');
      const { data, body } = parseFrontmatter(text);
      entries.push({
        folder,
        file: name,
        slug: basename(name, '.md'),
        relPath: `kb/${folder}/${name}`,
        data,
        body,
      });
    }
  }
  return entries;
}

export const SPECS_DIR = join(ROOT, 'specs');

/** Reads specs/ without validating. Returns empty arrays when the tier is absent. */
export function loadSpecs() {
  const read = (sub) => {
    const dir = join(SPECS_DIR, sub);
    let names;
    try {
      names = readdirSync(dir);
    } catch {
      return [];
    }
    return names
      .filter((n) => n.endsWith('.json') && !n.startsWith('_'))
      .sort()
      .map((n) => ({ rel: `specs/${sub}/${n}`, data: JSON.parse(readFileSync(join(dir, n), 'utf8')) }));
  };
  return { layers: read('layers'), architectures: read('architectures'), rulesets: read('rules') };
}

export const GENERATED_HEADER =
  '<!-- GENERATED by scripts/build-index.mjs — do not edit. Run `npm run index`. -->';
